---
- block:

    - name: Failing when timer_command is undefined
      fail:
          msg: Varible timer_command is not defined
      when: item.value.timer_command is undefined
      with_dict: "{{ timers }}"

    - name: Uploading service file
      template:
          src: service.j2
          dest: "/etc/systemd/system/{{ item.key }}.service"
          owner: root
          group: root
          mode: 0750
      with_dict: "{{ timers }}"

    - name: Uploading timer file
      template:
          src: timer.j2
          dest: "/etc/systemd/system/{{ item.key }}.timer"
          owner: root
          group: root
          mode: 0750
      with_dict: "{{ timers }}"

    - name: Enabling timers
      systemd:
          name: "{{ item.key }}.timer"
          state: started
          enabled: true
          masked: false
          daemon_reload: true
      with_dict: "{{ timers }}"

  when: timers is defined
